Repository jprichardson/node-fs-extra, pull requests merged in 2019-05, with the labels that each got.

#679 util/stat: fix max call stack size exceeded
  lib/util/__tests__/stat.test.js
  lib/util/stat.js
Labels: bug

#692 Use files array in package.json instead of .npmignore
  .npmignore
  package.json
Labels: enhancement

#690 Clarify docs for remove*()
  docs/remove-sync.md
  docs/remove.md
Labels: documentation, feature-remove
