Repository jprichardson/node-fs-extra, pull requests merged in 2020-02, with the labels that each got.

#747 Update fs promise shims to support latest Node functions
  README.md
  docs/fs-read-write-writev.md
  lib/fs/__tests__/multi-param.test.js
  lib/fs/index.js
Labels: promises

#633 Update dest atime after copy/copy-sync
  lib/copy-sync/__tests__/copy-sync-preserve-timestamp.test.js
  lib/copy-sync/copy-sync.js
  lib/copy/__tests__/copy-preserve-timestamp.test.js
  lib/copy/copy.js
Labels: feature-copy

#751 Drop old Node support
  .travis.yml
  appveyor.yml
  lib/copy-sync/__tests__/copy-sync-file.test.js
  lib/copy-sync/__tests__/copy-sync-preserve-timestamp.test.js
  lib/copy/__tests__/copy-permissions.test.js
  lib/copy/__tests__/copy-preserve-timestamp.test.js
  lib/copy/__tests__/ncp/ncp-error-perm.test.js
  lib/empty/index.js
  lib/ensure/file.js
  lib/ensure/symlink-type.js
  lib/fs/__tests__/copyFile.test.js
  lib/fs/__tests__/fs-integration.test.js
  lib/fs/__tests__/multi-param.test.js
  lib/fs/__tests__/realpath.test.js
  lib/fs/index.js
  lib/index.js
  lib/mkdirs/__tests__/chmod.test.js
  lib/mkdirs/__tests__/clobber.test.js
  lib/mkdirs/__tests__/issue-209.test.js
  lib/mkdirs/__tests__/mkdirp.test.js
  lib/mkdirs/__tests__/perm.test.js
  lib/mkdirs/__tests__/perm_sync.test.js
  lib/mkdirs/__tests__/race.test.js
  lib/mkdirs/__tests__/rel.test.js
  lib/mkdirs/__tests__/root.test.js
  lib/mkdirs/__tests__/sync.test.js
  lib/mkdirs/__tests__/umask.test.js
  lib/mkdirs/mkdirs-sync.js
  lib/mkdirs/mkdirs.js
  lib/move-sync/__tests__/move-sync.test.js
  lib/move/__tests__/move.test.js
  lib/remove/rimraf.js
  lib/util/buffer.js
  lib/util/utimes.js
  package.json
  test.js
Labels: semver-major

#755 copy*(): remove copyFileFallback
  lib/copy-sync/__tests__/copy-sync-preserve-timestamp.test.js
  lib/copy-sync/copy-sync.js
  lib/copy/__tests__/copy-preserve-timestamp.test.js
  lib/copy/copy.js
Labels: feature-copy

#760 Use at-least-node instead of homespun version sniffing
  lib/fs/__tests__/multi-param.test.js
  lib/util/__tests__/stat.test.js
  lib/util/stat.js
  package.json
Labels: enhancement

#763 Don't generate package-lock.json; instead of just ignoring it
  .gitignore
  .npmrc
Labels: meta

#764 Refactor internal stat utils
  lib/__tests__/promise.test.js
  lib/copy/__tests__/copy.test.js
  lib/util/stat.js
Labels: enhancement, feature-copy, feature-move

#756 BREAKING: Use internal fork of make-dir for mkdirs implementation
  lib/mkdirs/__tests__/clobber.test.js
  lib/mkdirs/__tests__/issue-93.test.js
  lib/mkdirs/__tests__/opts-undef.test.js
  lib/mkdirs/__tests__/return.test.js
  lib/mkdirs/__tests__/return_sync.test.js
  lib/mkdirs/__tests__/root.test.js
  lib/mkdirs/index.js
  lib/mkdirs/make-dir.js
  lib/mkdirs/mkdirs-sync.js
  lib/mkdirs/mkdirs.js
  lib/mkdirs/win32.js
Labels: feature-ensureDir

#766 Document all create*() aliases for ensure*() methods
  docs/ensureLink-sync.md
  docs/ensureLink.md
  docs/ensureSymlink-sync.md
  docs/ensureSymlink.md
Labels: documentation
